version: '3.8'

services:
    app:
        container_name: frutymax-php
        build:
            context: .
        restart: always
        expose:
            - "9000"
        env_file:
            - .env
        depends_on:
            - db
        networks:
            - laravel

    nginx:
        image: nginx:stable-alpine
        container_name: frutymax-nginx
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - .:/var/www/html
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
            - /etc/letsencrypt:/etc/letsencrypt:ro
        depends_on:
            - app
        networks:
            - laravel

    db:
        image: mysql:8.0
        container_name: frutymax-db
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: rootpass
            MYSQL_DATABASE: frutymax
            MYSQL_USER: frutyuser
            MYSQL_PASSWORD: secret
        volumes:
            - db_data:/var/lib/mysql
        networks:
            - laravel

volumes:
    db_data:

networks:
    laravel:
