version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
            target: app
        image: exloz_app:latest
        env_file:
            - .env
        restart: unless-stopped
        expose:
            - "9000"
        networks:
            - backend

    nginx:
        image: nginx:stable-alpine
        container_name: exloz_nginx
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - /etc/nginx/certs/exloz.site/fullchain.pem:/etc/nginx/certs/fullchain.pem:ro
            - /etc/nginx/certs/exloz.site/privkey.pem:/etc/nginx/certs/privkey.pem:ro
            - ./nginx/conf.d:/etc/nginx/conf.d:ro,Z
            - ./:/var/www/html:ro,Z
        depends_on:
            - app
        networks:
            - backend

    db:
        image: mysql:8.0
        container_name: exloz_mysql
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_DATABASE:    ${DB_DATABASE}
            MYSQL_USER:        ${DB_USERNAME}
            MYSQL_PASSWORD:    ${DB_PASSWORD}
        volumes:
            - mysql_data:/var/lib/mysql:Z
        ports:
            - "3306:3306"
        networks:
            - backend

networks:
    backend:
        driver: bridge

volumes:
    mysql_data:
        driver: local
