version: '3.8'

networks:
    # red interna para base de datos y PHP-FPM
    backend:
        driver: bridge
    # red proxy compartida con Traefik
    proxy:
        external: true

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
            target: app
        image: frutymax_app:latest
        env_file:
            - .env
        restart: unless-stopped

        # Exponemos sólo al proxy, no a puertos host
        expose:
            - "9000"

        # Conecta a ambas redes: proxy para Traefik, backend para DB
        networks:
            - proxy
            - backend
    web:
        image: nginx:stable-alpine
        depends_on: [ app ]
        networks: [ proxy, backend ]
        expose: [ "80" ]
        volumes:
            - ./:/var/www/html:ro,Z
            - ./nginx/conf.d/:/etc/nginx/conf.d:ro,Z

        # Labels de Traefik para publicar tu app en https://exloz.site
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.exloz.rule=Host(`frutymax.exloz.site`)"
            - "traefik.http.routers.exloz.entrypoints=websecure"
            - "traefik.http.routers.exloz.tls.certresolver=le"
            - "traefik.http.services.exloz.loadbalancer.server.port=80"


    db:
        image: mysql:8.0
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_DATABASE:    ${DB_DATABASE}
            MYSQL_USER:        ${DB_USERNAME}
            MYSQL_PASSWORD:    ${DB_PASSWORD}
        volumes:
            - mysql_data:/var/lib/mysql:Z
        networks:
            - backend

volumes:
    mysql_data:
        driver: local
